In [1]:
# Importing Pandas to create DataFrame
import pandas as pd
  
# Creating Empty DataFrame and Storing it in variable df
df = pd.DataFrame()
  
# Printing Empty DataFrame
print(df)

Empty DataFrame
Columns: []
Index: []

[tutorial source](https://www.geeksforgeeks.org/different-ways-to-create-pandas-dataframe/)

In [36]:
# initialize list elements
data = [10,20,30,40,50,70]
  
# Create the pandas DataFrame with column name is provided explicitly
df = pd.DataFrame(data, columns=['Numbers'])
df.loc[-1]=[33]
df.loc[-2]=[33]
#df = df.sort_index()  # sorting by index
df = df.reset_index()
df = df.drop('index', axis=1)
#df.loc[-2.5]=[33]
#df.index = df.index + 1  # shifting index
#df.index = df.index + 1  # shifting index
#df = df.sort_index()  # sorting by index
print(df)

   Numbers
0       10
1       20
2       30
3       40
4       50
5       70
6       33
7       33

In [6]:
# initialize list of lists
data = [['tom', 10], ['nick', 15], ['juli', 14]]
  
# Create the pandas DataFrame
df = pd.DataFrame(data, columns=['Name', 'Age'])
  
# print dataframe.
df

   Name  Age
0   tom   10
1  nick   15
2  juli   14

In [7]:
# initialize data of lists.
data = {'Name': ['Tom', 'nick', 'krish', 'jack'],
        'Age': [20, 21, 19, 18]}
  
# Create DataFrame
df = pd.DataFrame(data)
  
# Print the output.
df

    Name  Age
0    Tom   20
1   nick   21
2  krish   19
3   jack   18

In [8]:
# initialize data of lists.
data = {'Name': ['Tom', 'Jack', 'nick', 'juli'],
        'marks': [99, 98, 95, 90]}
  
# Creates pandas DataFrame.
df = pd.DataFrame(data, index=['rank1',
                               'rank2',
                               'rank3',
                               'rank4'])
  
# print the data
df

       Name  marks
rank1   Tom     99
rank2  Jack     98
rank3  nick     95
rank4  juli     90

In [12]:
# Initialize data to lists.
data = [{'a':None, 'b': 2, 'c': 3},
        {'a': 10, 'b': 20, 'c': 30}]
  
# Creates DataFrame.
df = pd.DataFrame(data,index=["First","Second"])
  
# Print the data
df

           a   b   c
First    NaN   2   3
Second  10.0  20  30

In [15]:
# Initialize lists data.
data = [{'a': 1, 'b': 2},
        {'a': 5, 'b': 10, 'c': 20}]
  
# With two column indices, values same
# as dictionary keys
df1 = pd.DataFrame(data, index=['first',
                                'second'],
                   columns=['a', 'b','c','d'])
   
# print for first data frame
print(df1)

        a   b     c   d
first   1   2   NaN NaN
second  5  10  20.0 NaN

In [20]:
# List1
Name = ['tom', 'krish', 'nick', 'juli']
  
# List2
Age = [25, 30, 26, 22]
  
# get the list of tuples from two lists.
# and merge them by using zip().
list_of_tuples = list(zip(Name, Age))
  
# Assign data to tuples.
print(list_of_tuples)
  
  
# Converting lists of tuples into
# pandas Dataframe.
df = pd.DataFrame(list_of_tuples,
                  columns=['Name', 'Age'],index=[f"#{i}" for i in range(4)])
  
# Print data.
df

[('tom', 25), ('krish', 30), ('nick', 26), ('juli', 22)]

     Name  Age
#0    tom   25
#1  krish   30
#2   nick   26
#3   juli   22

In [25]:
# Initialize data to series.
d =  pd.Series([10, 20, 30, 40])
# creates Dataframe.
df = pd.DataFrame(d,columns=["a"])
  
# print the data.
df

    a
0  10
1  20
2  30
3  40

In [2]:
import pandas as pd
# Initialize data to Dicts of series.
d = {'one': pd.Series([10, 20, 30, 40],
                      index=['a', 'b', 'c', 'd']),
     'two': pd.Series([10, 20, 30, 40],
                      index=['a', 'b', 'c', 'd'])}
  
# creates Dataframe.
df = pd.DataFrame(d)
  
# print the data.
df["three"] = df.apply(lambda row:row['one']+1,axis=1)
df

   one  two  three
a   10   10     11
b   20   20     21
c   30   30     31
d   40   40     41

In [16]:
df.loc['e']=[1,2,3]  # adding a row
#df.drop(index=-1,inplace=True)
#df.index = df.index + 1  # shifting index
df = df.sort_index()  # sorting by index
df

   one  two  three
a   10   10     11
b   20   20     21
c   30   30     31
d   40   40     41
e    1    2      3

## Adding a row

In [17]:
df.loc['f']=[1,2,3]  # adding a row
#df.drop(index=-1,inplace=True)
#df.index = df.index + 1  # shifting index
df = df.sort_index()  # sorting by index
df

   one  two  three
a   10   10     11
b   20   20     21
c   30   30     31
d   40   40     41
e    1    2      3
f    1    2      3